export APP_PORT=8001
export USER_MICROSERVICE_HOST=127.0.0.1
export USER_MICROSERVICE_PORT=8002

export CUSTOMER_MICROSERVICE_HOST=amqp://admin:admin@localhost:5672
export CUSTOMER_MICROSERVICE_QUEUE_NAME=customer_queue
